import Testing
@testable import VideoVortexCore

// MARK: - SRTParser Tests
// Covers every edge case listed in §13 of VVXPhase3Roadmap.md.

@Suite("SRTParser")
struct SRTParserTests {

    // MARK: - Basic parse

    @Test("Parses a standard well-formed SRT file")
    func basicParse() {
        let srt = """
        1
        00:00:01,000 --> 00:00:04,000
        Hello, world.

        2
        00:00:05,000 --> 00:00:08,000
        This is a subtitle.
        """
        let blocks = SRTParser.parse(srt)
        #expect(blocks.count == 2)
        #expect(blocks[0].index     == 1)
        #expect(blocks[0].startTime == "00:00:01,000")
        #expect(blocks[0].endTime   == "00:00:04,000")
        #expect(blocks[0].text      == "Hello, world.")
        #expect(blocks[1].index     == 2)
        #expect(blocks[1].text      == "This is a subtitle.")
    }

    @Test("Returns empty array for empty input")
    func emptyInput() {
        #expect(SRTParser.parse("").isEmpty)
    }

    // MARK: - Multi-line blocks

    @Test("Joins multi-line subtitle text with spaces")
    func multiLineBlock() {
        let srt = """
        1
        00:00:01,000 --> 00:00:06,000
        First line of the
        multi-line block.
        Third line here.
        """
        let blocks = SRTParser.parse(srt)
        #expect(blocks.count == 1)
        #expect(blocks[0].text == "First line of the multi-line block. Third line here.")
    }

    // MARK: - UTF-8 content

    @Test("Preserves emoji in subtitle text")
    func utf8Emoji() {
        let srt = """
        1
        00:00:01,000 --> 00:00:03,000
        Hello 🔥 World 🚀
        """
        let blocks = SRTParser.parse(srt)
        #expect(blocks.count == 1)
        #expect(blocks[0].text.contains("🔥"))
        #expect(blocks[0].text.contains("🚀"))
    }

    @Test("Preserves CJK characters in subtitle text")
    func utf8CJK() {
        let srt = """
        1
        00:00:01,000 --> 00:00:03,000
        人工知能について
        """
        let blocks = SRTParser.parse(srt)
        #expect(blocks.count == 1)
        #expect(blocks[0].text == "人工知能について")
    }

    @Test("Preserves Arabic RTL text in subtitle")
    func utf8Arabic() {
        let srt = """
        1
        00:00:01,000 --> 00:00:03,000
        مرحبا بالعالم
        """
        let blocks = SRTParser.parse(srt)
        #expect(blocks.count == 1)
        #expect(blocks[0].text == "مرحبا بالعالم")
    }

    // MARK: - HTML entities

    @Test("Decodes &amp; to &")
    func htmlEntityAmpersand() {
        let srt = "1\n00:00:01,000 --> 00:00:03,000\nAT&amp;T announces new plan\n"
        let blocks = SRTParser.parse(srt)
        #expect(blocks[0].text == "AT&T announces new plan")
    }

    @Test("Decodes &lt; and &gt; angle bracket entities")
    func htmlEntityAngles() {
        let srt = "1\n00:00:01,000 --> 00:00:03,000\nvalue &lt; 10 &gt; 0\n"
        let blocks = SRTParser.parse(srt)
        #expect(blocks[0].text == "value < 10 > 0")
    }

    @Test("Decodes &#39; to apostrophe")
    func htmlEntityApos() {
        let srt = "1\n00:00:01,000 --> 00:00:03,000\nit&#39;s a test\n"
        let blocks = SRTParser.parse(srt)
        #expect(blocks[0].text == "it's a test")
    }

    @Test("Decodes &quot; to double quote")
    func htmlEntityQuot() {
        let srt = "1\n00:00:01,000 --> 00:00:03,000\nHe said &quot;hello&quot;\n"
        let blocks = SRTParser.parse(srt)
        #expect(blocks[0].text == "He said \"hello\"")
    }

    // MARK: - Auto-generated timing tags

    @Test("Strips yt-dlp word-level timestamp tags")
    func autoGeneratedTimingTags() {
        let srt = """
        1
        00:14:32,000 --> 00:14:37,000
        <00:14:32.040>when we <00:14:33.120>talk about <00:14:34.080>artificial intelligence
        """
        let blocks = SRTParser.parse(srt)
        #expect(blocks.count == 1)
        #expect(blocks[0].text == "when we talk about artificial intelligence")
    }

    @Test("Strips <c> colour positioning tags")
    func autoGeneratedColourTags() {
        let srt = """
        1
        00:00:01,000 --> 00:00:04,000
        <c.colorE5E5E5>This is highlighted text</c>
        """
        let blocks = SRTParser.parse(srt)
        #expect(blocks.count == 1)
        #expect(blocks[0].text == "This is highlighted text")
    }

    @Test("Collapses extra spaces after tag removal")
    func spacesAfterTagRemoval() {
        let srt = "1\n00:00:01,000 --> 00:00:03,000\n<c>word1</c> <c>word2</c>\n"
        let blocks = SRTParser.parse(srt)
        // Should not have double-spaces in the result
        #expect(blocks[0].text == "word1 word2")
        #expect(!blocks[0].text.contains("  "))
    }

    // MARK: - Empty blocks

    @Test("Drops blocks with no text content")
    func emptyBlocks() {
        let srt = """
        1
        00:00:01,000 --> 00:00:04,000

        2
        00:00:05,000 --> 00:00:08,000
        Valid subtitle here.
        """
        let blocks = SRTParser.parse(srt)
        #expect(blocks.count == 1)
        #expect(blocks[0].index == 2)
        #expect(blocks[0].text == "Valid subtitle here.")
    }

    @Test("Drops blocks that are empty after tag stripping")
    func blocksEmptyAfterStripping() {
        let srt = """
        1
        00:00:01,000 --> 00:00:04,000
        <00:00:01.000><00:00:02.000>

        2
        00:00:05,000 --> 00:00:08,000
        Real text here.
        """
        let blocks = SRTParser.parse(srt)
        #expect(blocks.count == 1)
        #expect(blocks[0].index == 2)
    }

    // MARK: - Windows CRLF line endings

    @Test("Parses SRT with Windows CRLF line endings")
    func windowsLineEndings() {
        let srt = "1\r\n00:00:01,000 --> 00:00:04,000\r\nHello world.\r\n\r\n2\r\n00:00:05,000 --> 00:00:08,000\r\nSecond block.\r\n"
        let blocks = SRTParser.parse(srt)
        #expect(blocks.count == 2)
        #expect(blocks[0].text == "Hello world.")
        #expect(blocks[1].text == "Second block.")
    }

    @Test("Parses SRT with bare CR line endings")
    func bareCarriageReturn() {
        let srt = "1\r00:00:01,000 --> 00:00:03,000\rHello CR.\r\r2\r00:00:04,000 --> 00:00:06,000\rSecond.\r"
        let blocks = SRTParser.parse(srt)
        #expect(blocks.count == 2)
        #expect(blocks[0].text == "Hello CR.")
    }

    // MARK: - Duplicate indices

    @Test("Keeps all blocks even when index numbers are duplicated")
    func duplicateIndices() {
        let srt = """
        1
        00:00:01,000 --> 00:00:03,000
        First block.

        1
        00:00:03,000 --> 00:00:05,000
        Duplicate index block.
        """
        let blocks = SRTParser.parse(srt)
        #expect(blocks.count == 2)
        #expect(blocks[0].text == "First block.")
        #expect(blocks[1].text == "Duplicate index block.")
    }

    // MARK: - toPlainText

    @Test("toPlainText joins all block text with spaces")
    func toPlainText() {
        let blocks = [
            SRTBlock(index: 1, startTime: "00:00:01,000", endTime: "00:00:04,000",
                     startSeconds: 1.0, endSeconds: 4.0, text: "Hello world."),
            SRTBlock(index: 2, startTime: "00:00:05,000", endTime: "00:00:08,000",
                     startSeconds: 5.0, endSeconds: 8.0, text: "This is a test."),
        ]
        let result = SRTParser.toPlainText(blocks)
        #expect(result == "Hello world. This is a test.")
    }

    @Test("toPlainText returns empty string for empty block array")
    func toPlainTextEmpty() {
        #expect(SRTParser.toPlainText([]) == "")
    }

    // MARK: - Timestamp parsing

    @Test("Parses HH:MM:SS,mmm to correct decimal seconds")
    func timestampParsing() {
        // 00:14:32,000 = 0*3600 + 14*60 + 32.0 = 872.0 seconds
        let result = SRTParser.parseTimestamp("00:14:32,000")
        #expect(result == 872.0)
    }

    @Test("Parses fractional milliseconds correctly")
    func timestampFractional() {
        // 00:00:03,500 = 3.5 seconds
        let result = SRTParser.parseTimestamp("00:00:03,500")
        #expect(result == 3.5)
    }

    @Test("Parses yt-dlp dot-separated timestamp format")
    func timestampDotSeparator() {
        // yt-dlp auto-captions use dots instead of commas
        let result = SRTParser.parseTimestamp("00:14:32.040")
        #expect(result != nil)
        if let secs = result {
            #expect(abs(secs - 872.04) < 0.001)
        }
    }

    @Test("Returns nil for completely malformed timestamp")
    func timestampMalformed() {
        #expect(SRTParser.parseTimestamp("not-a-timestamp") == nil)
        #expect(SRTParser.parseTimestamp("") == nil)
        #expect(SRTParser.parseTimestamp("00:14") == nil)
    }

    @Test("Maps 1 hour exactly to 3600 seconds")
    func timestampOneHour() {
        #expect(SRTParser.parseTimestamp("01:00:00,000") == 3_600.0)
    }

    @Test("Maps 1 hour 14 minutes 32 seconds correctly")
    func timestampComplex() {
        // 1*3600 + 14*60 + 32 = 4472.0
        let result = SRTParser.parseTimestamp("01:14:32,000")
        #expect(result == 4_472.0)
    }

    // MARK: - startSeconds / endSeconds in parsed blocks

    @Test("Block startSeconds and endSeconds match parsed timestamps")
    func blockSeconds() {
        let srt = """
        1
        00:14:32,000 --> 00:14:47,000
        The key question is about AGI.
        """
        let blocks = SRTParser.parse(srt)
        #expect(blocks.count == 1)
        #expect(blocks[0].startSeconds == 872.0)
        #expect(blocks[0].endSeconds   == 887.0)
    }

    @Test("Blocks are returned in source order")
    func sourceOrder() {
        let srt = """
        1
        00:00:01,000 --> 00:00:02,000
        Alpha.

        2
        00:00:03,000 --> 00:00:04,000
        Beta.

        3
        00:00:05,000 --> 00:00:06,000
        Gamma.
        """
        let blocks = SRTParser.parse(srt)
        #expect(blocks.count == 3)
        #expect(blocks[0].text == "Alpha.")
        #expect(blocks[1].text == "Beta.")
        #expect(blocks[2].text == "Gamma.")
        #expect(blocks[0].startSeconds < blocks[1].startSeconds)
        #expect(blocks[1].startSeconds < blocks[2].startSeconds)
    }
}
