import Foundation

/// The type of subtitle track that produced the `transcriptBlocks` in a `SenseResult`.
///
/// Agents should prefer `.manual` transcripts for accuracy; `.auto` transcripts
/// are generated by the platform and may contain errors.
/// `.local` means blocks were read from the user’s archive (vault) `.srt`, not yt-dlp’s sense output dir.
/// `.none` is the definitive "no usable transcript" signal — empty `transcriptBlocks`
/// with this source means the video has no subtitle track, not a parser failure.
public enum TranscriptSource: String, Codable, Sendable, CaseIterable {
    /// Auto-generated captions produced by the platform (e.g. YouTube's speech-to-text).
    case auto = "auto"
    /// Manually written subtitles uploaded by the creator or provided by the platform.
    case manual = "manual"
    /// Community-contributed subtitles.
    case community = "community"
    /// Subtitle text was read from an on-disk file in the user’s archive / vault
    /// (e.g. after `vvx fetch --archive`), not from yt-dlp’s sense output directory.
    /// Treat as authoritative transcript text for indexing when network subs are missing.
    case local = "local"
    /// No usable subtitle track was found or downloaded.
    /// `transcriptBlocks` will be empty and `estimatedTokens` will be `nil` when this is set.
    case none = "none"
    /// A subtitle file was found on disk but the source type could not be determined
    /// (e.g. the yt-dlp info dict did not list the track in either `subtitles` or
    /// `automatic_captions`).
    case unknown = "unknown"
}
